services:
  backend:
    build: ./backend
    volumes:
      - static_volume:/app/static
    environment:
      # Database URL for PostgreSQL
      DATABASE_URL: postgresql://${YC_DB_USER:-postgres}:${YC_DB_PASSWORD:-postgres}@${YC_DB_HOST:-localhost}:${YC_DB_PORT:-5432}/${YC_DB_NAME:-zubroslov}
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000
      --ssl-keyfile=${SSL_KEY_PATH:-/dev/null}
      --ssl-certfile=${SSL_CERT_PATH:-/dev/null}"

volumes:
  static_volume:
