name: Deploy to Test Environment
on:
  push:
    branches: [develop]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment_name: "Test"
      branch: "develop"
      api_url: "https://api-test.zubroslov.ru/api"
      server_url: "https://api-test.zubroslov.ru"
      bucket_name: "test.zubroslov.ru"
      image_tag: "test"
      env_param: "--env test"
    secrets:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      YC_STORAGE_ACCESS_KEY: ${{ secrets.YC_STORAGE_ACCESS_KEY }}
      YC_STORAGE_SECRET_KEY: ${{ secrets.YC_STORAGE_SECRET_KEY }}
      YC_SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
      YC_REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}
