name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: |
          cd frontend
          npm ci
          npm run build
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "frontend/dist/*"
          target: "/var/www/zubroslov/frontend"

  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3-pip
          pip install pyjwt

      - name: Login to Yandex Container Registry
        env:
          YC_SA_KEY: ${{ secrets.YC_SA_KEY }}
          YC_REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}
        run: |
          # Генерация JWT-токена
          TOKEN=$(echo "$YC_SA_KEY" | jq -r .service_account_key | base64 -d | jq -r .private_key |
            openssl pkcs8 -inform PEM -nocrypt -topk8 |
            jwt encode --alg PS256 --secret @- -p "aud=https://iam.api.cloud.yandex.net/iam/v1/tokens&iss=${YC_SA_KEY}" -)

          # Аутентификация в Docker
          echo $TOKEN | docker login --username iam --password-stdin cr.yandex

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/zubroslov-api:latest
